### ISSUE TITLE
libtensorflow_framework.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Hasindri** [diviswen/Point2SpatialCapsule#1]
when I try " !python train.py" I get the following error with .so files,

```
FLAGS: Namespace(augment=False, batch_size=16, decay_rate=0.7, decay_step=200000, gpu=0, iter_routing=1, learning_rate=0.001, log_dir='log', max_epoch=1, model='p2sc', modelnet10=False, momentum=0.9, normal=False, num_point=1024, optimizer='adam', spread=False, weight_decay=False)
Traceback (most recent call last):
  File "train.py", line 66, in <module>
    MODEL = importlib.import_module(FLAGS.model) # import network module
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/content/Point2SpatialCapsule/p2sc.py", line 11, in <module>
    import tf_approxmatch
  File "/content/Point2SpatialCapsule/./external/structural_losses/tf_approxmatch.py", line 7, in <module>
    approxmatch_module = tf.load_op_library(osp.join(base_dir, 'tf_approxmatch_so.so'))
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
**tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so: cannot open shared object file: No such file or directory**

```

I am running the code on google Colab (using python 3.7 and tensorflow 1.15.2) and I have installed necessary cuda 8.0 files. I don't think the issue is regarding any of the library version issues. The file that the error says missing "ibtensorflow_framework.so" is there.

its in "/usr/local/lib/python3.7/dist-packages/tensorflow" and I have used symbolic links as follows

`# Create a symlink so both .so and .so.2 point to the same file
!ln -s libtensorflow_framework.so.2 libtensorflow_framework.so`

I am unable to solve this issue or rewrite the code because .so files aren't readable. Can you help me understand where the issue exists? is it because .so files aren't in the folder they should be? a tensorflow, python, cuda compatibility issue? or some other issue?

if you have code written for newer library versions, please share with me

thank you.

**Comment by diviswen** [comment]
It looks like that this issue may related to your TF environment.
The error happens when loading "'tf_approxmatch_so.so":
```
  File "/content/Point2SpatialCapsule/./external/structural_losses/tf_approxmatch.py", line 7, in <module>
    approxmatch_module = tf.load_op_library(osp.join(base_dir, 'tf_approxmatch_so.so'))
```
The above code then goes to "load_library.py" which is in your tensorflow installation folder:
```
  File "/tensorflow-1.15.2/python3.7/tensorflow_core/python/framework/load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
```
I am not sure wethter the "library_filename" means the missing file "libtensorflow_framework.so", but surely it is a file neccessary and related to TF 1.15 env.

Several suggestions:
1. Try TF 1.14.
2. "tf_approxmatch.py" is used for estimating earth mover's distance (EMD) between two point clouds. So another walk around is to replace the EMD in our code with some other EMD implementation the you can find. You can find it at Ln166 & Ln167 in p2sc.py:
https://github.com/diviswen/Point2SpatialCapsule/blob/0c0b87bf65b0a38774c41474cac1ed7ca33c9f1d/p2sc.py#L166
